// Mock data structure for doctors and specialties
// This is designed to easily integrate with MongoDB/Firebase in the future

export const specialties = [
  {
    id: "neurology",
    name: "Neurology",
    icon: "brain",
    description: "Brain & Nervous System",
    color: "from-purple-500 to-purple-600",
  },
  {
    id: "cardiology",
    name: "Cardiology",
    icon: "heart",
    description: "Heart & Cardiovascular",
    color: "from-red-500 to-red-600",
  },
  {
    id: "orthopedics",
    name: "Orthopedics",
    icon: "bone",
    description: "Bones & Joints",
    color: "from-yellow-500 to-yellow-600",
  },
  {
    id: "neurosurgery",
    name: "Neurosurgery",
    icon: "spinal",
    description: "Spinal & Neurological Surgery",
    color: "from-blue-500 to-blue-600",
  },
  {
    id: "ophthalmology",
    name: "Ophthalmology",
    icon: "eye",
    description: "Eye Care",
    color: "from-green-500 to-green-600",
  },
  {
    id: "cosmetic",
    name: "Cosmetic Surgery",
    icon: "surgery",
    description: "Cosmetic & Plastic Surgery",
    color: "from-pink-500 to-pink-600",
  },
  {
    id: "dentistry",
    name: "Dentistry",
    icon: "dental",
    description: "Dental Care",
    color: "from-cyan-500 to-cyan-600",
  },
  {
    id: "anesthesia",
    name: "Anesthesiology",
    icon: "anasthesia",
    description: "Anesthesia & Pain Management",
    color: "from-indigo-500 to-indigo-600",
  },
  {
    id: "pulmonology",
    name: "Pulmonology",
    icon: "lungs",
    description: "Lungs & Respiratory",
    color: "from-sky-500 to-sky-600",
  },
  {
    id: "hepatology",
    name: "Hepatology",
    icon: "liver",
    description: "Liver & Digestive",
    color: "from-amber-500 to-amber-600",
  },
  {
    id: "ent",
    name: "ENT",
    icon: "ent",
    description: "Ear, Nose & Throat",
    color: "from-orange-500 to-orange-600",
  },
  {
    id: "nephrology",
    name: "Nephrology",
    icon: "nephrology",
    description: "Kidney & Urology",
    color: "from-teal-500 to-teal-600",
  },
  {
    id: "gastroenterology",
    name: "Gastroenterology",
    icon: "stomach",
    description: "Stomach & Digestive",
    color: "from-rose-500 to-rose-600",
  },
  {
    id: "urology",
    name: "Urology",
    icon: "ureter",
    description: "Urinary System",
    color: "from-violet-500 to-violet-600",
  },
  {
    id: "pancreas",
    name: "Pancreatology",
    icon: "pancreas",
    description: "Pancreas & Endocrine",
    color: "from-sky-400 to-sky-700",
  },
  {
    id: "pediatrics",
    name: "Pediatrics",
    icon: "child",
    description: "Children's Health",
    color: "from-sky-400 to-sky-700",
  },
];

// Mock doctor data - organized by specialty
export const doctorsData = {
  neurology: [
    {
      id: "doc-001",
      name: "Dr. Sarah Mitchell",
      specialty: "Neurologist",
      specialtyId: "neurology",
      rating: 4.8,
      reviews: 234,
      experience: "12+ years",
      image: "https://i.pravatar.cc/150?img=1",
      bio: "Specializes in migraine management and neurological disorders",
      availability: "Mon-Fri, 9 AM - 5 PM",
    },
    {
      id: "doc-002",
      name: "Dr. James Anderson",
      specialty: "Neurologist",
      specialtyId: "neurology",
      rating: 4.6,
      reviews: 189,
      experience: "10+ years",
      image: "https://i.pravatar.cc/150?img=2",
      bio: "Expert in Parkinson's disease and movement disorders",
      availability: "Mon-Sat, 10 AM - 6 PM",
    },
    {
      id: "doc-003",
      name: "Dr. Emily Chen",
      specialty: "Neurologist",
      specialtyId: "neurology",
      rating: 4.9,
      reviews: 312,
      experience: "15+ years",
      image: "https://i.pravatar.cc/150?img=3",
      bio: "Renowned for stroke recovery and rehabilitation",
      availability: "Tue-Sun, 2 PM - 8 PM",
    },
  ],
  cardiology: [
    {
      id: "doc-004",
      name: "Dr. Robert Johnson",
      specialty: "Cardiologist",
      specialtyId: "cardiology",
      rating: 4.9,
      reviews: 456,
      experience: "18+ years",
      image: "https://i.pravatar.cc/150?img=4",
      bio: "Expert in interventional cardiology and heart transplants",
      availability: "Mon-Thu, 8 AM - 4 PM",
    },
    {
      id: "doc-005",
      name: "Dr. Lisa Wong",
      specialty: "Cardiologist",
      specialtyId: "cardiology",
      rating: 4.7,
      reviews: 289,
      experience: "14+ years",
      image: "https://i.pravatar.cc/150?img=5",
      bio: "Specializes in heart failure management",
      availability: "Mon-Fri, 9 AM - 5 PM",
    },
    {
      id: "doc-006",
      name: "Dr. Michael Brown",
      specialty: "Cardiologist",
      specialtyId: "cardiology",
      rating: 4.8,
      reviews: 367,
      experience: "16+ years",
      image: "https://i.pravatar.cc/150?img=6",
      bio: "Pioneer in preventive cardiology and risk assessment",
      availability: "Wed-Sun, 10 AM - 6 PM",
    },
  ],
  orthopedics: [
    {
      id: "doc-007",
      name: "Dr. David Martinez",
      specialty: "Orthopedic Surgeon",
      specialtyId: "orthopedics",
      rating: 4.8,
      reviews: 278,
      experience: "11+ years",
      image: "https://i.pravatar.cc/150?img=7",
      bio: "Specialist in sports medicine and joint replacement",
      availability: "Mon-Fri, 9 AM - 5 PM",
    },
    {
      id: "doc-008",
      name: "Dr. Jennifer Lee",
      specialty: "Orthopedic Surgeon",
      specialtyId: "orthopedics",
      rating: 4.7,
      reviews: 245,
      experience: "13+ years",
      image: "https://i.pravatar.cc/150?img=8",
      bio: "Expert in spine surgery and orthopedic trauma",
      availability: "Tue-Sat, 10 AM - 6 PM",
    },
  ],
  ophthalmology: [
    {
      id: "doc-009",
      name: "Dr. William Garcia",
      specialty: "Ophthalmologist",
      specialtyId: "ophthalmology",
      rating: 4.9,
      reviews: 392,
      experience: "17+ years",
      image: "https://i.pravatar.cc/150?img=9",
      bio: "Specializes in LASIK surgery and cataract removal",
      availability: "Mon-Thu, 8 AM - 4 PM",
    },
    {
      id: "doc-010",
      name: "Dr. Amanda White",
      specialty: "Ophthalmologist",
      specialtyId: "ophthalmology",
      rating: 4.6,
      reviews: 201,
      experience: "9+ years",
      image: "https://i.pravatar.cc/150?img=10",
      bio: "Expert in retinal diseases and diabetic eye care",
      availability: "Mon-Fri, 9 AM - 5 PM",
    },
  ],
  dentistry: [
    {
      id: "doc-011",
      name: "Dr. Christopher Davis",
      specialty: "Dentist",
      specialtyId: "dentistry",
      rating: 4.8,
      reviews: 324,
      experience: "12+ years",
      image: "https://i.pravatar.cc/150?img=11",
      bio: "Specialist in cosmetic dentistry and implants",
      availability: "Mon-Sat, 9 AM - 6 PM",
    },
    {
      id: "doc-012",
      name: "Dr. Rachel Green",
      specialty: "Dentist",
      specialtyId: "dentistry",
      rating: 4.7,
      reviews: 267,
      experience: "10+ years",
      image: "https://i.pravatar.cc/150?img=12",
      bio: "Expert in orthodontics and pediatric dentistry",
      availability: "Tue-Sun, 10 AM - 7 PM",
    },
  ],
  pulmonology: [
    {
      id: "doc-013",
      name: "Dr. Patricia Taylor",
      specialty: "Pulmonologist",
      specialtyId: "pulmonology",
      rating: 4.8,
      reviews: 198,
      experience: "11+ years",
      image: "https://i.pravatar.cc/150?img=13",
      bio: "Specializes in asthma and COPD management",
      availability: "Mon-Fri, 9 AM - 5 PM",
    },
    {
      id: "doc-014",
      name: "Dr. Kevin Rodriguez",
      specialty: "Pulmonologist",
      specialtyId: "pulmonology",
      rating: 4.7,
      reviews: 156,
      experience: "9+ years",
      image: "https://i.pravatar.cc/150?img=14",
      bio: "Expert in interstitial lung disease and pulmonary fibrosis",
      availability: "Wed-Sat, 1 PM - 7 PM",
    },
  ],
  neurosurgery: [
    {
      id: "doc-015",
      name: "Dr. Marcus Phillips",
      specialty: "Neurosurgeon",
      specialtyId: "neurosurgery",
      rating: 4.9,
      reviews: 289,
      experience: "20+ years",
      image: "https://i.pravatar.cc/150?img=15",
      bio: "Pioneer in minimally invasive spinal surgery",
      availability: "Mon-Thu, 8 AM - 4 PM",
    },
  ],
  cosmetic: [
    {
      id: "doc-016",
      name: "Dr. Victoria Thompson",
      specialty: "Plastic Surgeon",
      specialtyId: "cosmetic",
      rating: 4.8,
      reviews: 445,
      experience: "16+ years",
      image: "https://i.pravatar.cc/150?img=16",
      bio: "Specializes in facial reconstruction and body contouring",
      availability: "Mon-Fri, 10 AM - 6 PM",
    },
  ],
  anesthesia: [
    {
      id: "doc-017",
      name: "Dr. Steven Cruz",
      specialty: "Anesthesiologist",
      specialtyId: "anesthesia",
      rating: 4.7,
      reviews: 134,
      experience: "11+ years",
      image: "https://i.pravatar.cc/150?img=17",
      bio: "Expert in regional anesthesia and pain management",
      availability: "Mon-Fri, 7 AM - 3 PM",
    },
  ],
  hepatology: [
    {
      id: "doc-018",
      name: "Dr. Angela Murphy",
      specialty: "Hepatologist",
      specialtyId: "hepatology",
      rating: 4.8,
      reviews: 167,
      experience: "13+ years",
      image: "https://i.pravatar.cc/150?img=18",
      bio: "Specializes in liver disease and hepatitis management",
      availability: "Tue-Fri, 10 AM - 5 PM",
    },
  ],
  ent: [
    {
      id: "doc-019",
      name: "Dr. Daniel Stewart",
      specialty: "ENT Specialist",
      specialtyId: "ent",
      rating: 4.7,
      reviews: 201,
      experience: "10+ years",
      image: "https://i.pravatar.cc/150?img=19",
      bio: "Expert in endoscopic sinus surgery",
      availability: "Mon-Sat, 9 AM - 5 PM",
    },
  ],
  nephrology: [
    {
      id: "doc-020",
      name: "Dr. Hannah Roberts",
      specialty: "Nephrologist",
      specialtyId: "nephrology",
      rating: 4.8,
      reviews: 176,
      experience: "12+ years",
      image: "https://i.pravatar.cc/150?img=20",
      bio: "Specializes in kidney disease and dialysis management",
      availability: "Mon-Fri, 9 AM - 5 PM",
    },
  ],
  gastroenterology: [
    {
      id: "doc-021",
      name: "Dr. Nathan Scott",
      specialty: "Gastroenterologist",
      specialtyId: "gastroenterology",
      rating: 4.8,
      reviews: 234,
      experience: "14+ years",
      image: "https://i.pravatar.cc/150?img=21",
      bio: "Expert in endoscopy and inflammatory bowel disease",
      availability: "Mon-Thu, 9 AM - 5 PM",
    },
  ],
  urology: [
    {
      id: "doc-022",
      name: "Dr. Olivia Jackson",
      specialty: "Urologist",
      specialtyId: "urology",
      rating: 4.7,
      reviews: 189,
      experience: "11+ years",
      image: "https://i.pravatar.cc/150?img=22",
      bio: "Specializes in urological oncology and prostate disease",
      availability: "Tue-Sat, 10 AM - 6 PM",
    },
  ],
  pancreas: [
    {
      id: "doc-023",
      name: "Dr. Samuel Carter",
      specialty: "Pancreatologist",
      specialtyId: "pancreas",
      rating: 4.6,
      reviews: 98,
      experience: "10+ years",
      image: "https://i.pravatar.cc/150?img=23",
      bio: "Expertise in pancreatic disorders and endocrine research",
      availability: "Mon-Fri, 9 AM - 4 PM",
    },
  ],
  pediatrics: [
    {
      id: "doc-024",
      name: "Dr. Emily Rivera",
      specialty: "Pediatrician",
      specialtyId: "pediatrics",
      rating: 4.9,
      reviews: 210,
      experience: "12+ years",
      image: "https://i.pravatar.cc/150?img=24",
      bio: "Caring for newborns, infants, and children with compassion",
      availability: "Tue-Fri, 8 AM - 3 PM",
    },
  ],
};

// Helper function to get doctors by specialty
export const getDoctorsBySpecialty = (specialtyId) => {
  return doctorsData[specialtyId] || [];
};

// Helper function to get all doctors
export const getAllDoctors = () => {
  return Object.values(doctorsData).flat();
};

// Helper function to search doctors
export const searchDoctors = (query) => {
  const allDoctors = getAllDoctors();
  return allDoctors.filter(
    (doctor) =>
      doctor.name.toLowerCase().includes(query.toLowerCase()) ||
      doctor.specialty.toLowerCase().includes(query.toLowerCase())
  );
};
